name: Purple Monkey Visual Creations
favicon: null
layout_spectrum: 0.9321678876876831
typography_spectrum: 0.43062309524975717
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9478583263698965
  lightness: 0.10013251286000013
  saturation: 0.9064038663636893
  rhythmicContrast: 0.7224066993221641
purpose: []
