name: Purple Monkey Visual Creations
favicon: null
layout_spectrum: 0.9321678876876831
typography_spectrum: 0.43062309524975717
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff9fd'
    - '#273d45'
    - '#697c83'
    - '#4a6f10'
    - '#cea47c'
  brandStrength: 0.9478583263698965
  lightness: 0.10013251286000013
  saturation: 0.9064038663636893
  rhythmicContrast: 0.7224066993221641
purpose: []
